services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green-lab-fe
    ports:
      - "3002:3002"
    restart: always
    environment:
      - NODE_ENV=production