import AppHeader from "@/component/layout/header/AppHeader";
import AppFooter from "@/component/layout/AppFooter";
import ContactFloatingButton from "@/component/ContactFloatingButton";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
export const metadata = {
  title: "Green Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <>
     <AppHeader />
     <main>
       <section>{children}</section>
       <ContactFloatingButton />
     </main>
     <AppFooter />
   </>
  );
}
